
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 绑定类型
 */
const (
    /**
     * 不绑定
     */
    BindType_None = 0;
    /**
     * 拾取绑定
     */
    BindType_PickupBind = 1;
    /**
     * 装备绑定
     */
    BindType_EquipBind = 2;
)

