
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 货币类型
 */
const (
    /**
     * 金币
     */
    CurrencyType_Coin = 1;
    /**
     * 钻石
     */
    CurrencyType_Diamond = 2;
    /**
     * 公会币
     */
    CurrencyType_GuildCoin = 3;
    /**
     * 联盟币
     */
    CurrencyType_AllianceCoin = 4;
    /**
     * 荣誉点
     */
    CurrencyType_HonorPoint = 5;
)

