
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 过期类型
 */
const (
    /**
     * 永久
     */
    ExpireType_Permanent = 0;
    /**
     * 时长
     */
    ExpireType_Duration = 1;
    /**
     * 固定日期
     */
    ExpireType_FixedDate = 2;
)

