
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type GlobalConfig struct {
    TeamMaxMembers int32
    TeamInviteMaxCount int32
    TeamInviteExpireTime int32
    EnableCrossServerTeam bool
}

const TypeId_GlobalConfig = -958250779

func (*GlobalConfig) GetTypeId() int32 {
    return -958250779
}

func NewGlobalConfig(_buf map[string]interface{}) (_v *GlobalConfig, err error) {
    _v = &GlobalConfig{}
    { var _ok_ bool; var __json_team_max_members__ interface{}; if __json_team_max_members__, _ok_ = _buf["team_max_members"]; !_ok_ || __json_team_max_members__ == nil { err = errors.New("team_max_members error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_team_max_members__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.TeamMaxMembers = __x__ }}
    { var _ok_ bool; var __json_team_invite_max_count__ interface{}; if __json_team_invite_max_count__, _ok_ = _buf["team_invite_max_count"]; !_ok_ || __json_team_invite_max_count__ == nil { err = errors.New("team_invite_max_count error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_team_invite_max_count__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.TeamInviteMaxCount = __x__ }}
    { var _ok_ bool; var __json_team_invite_expire_time__ interface{}; if __json_team_invite_expire_time__, _ok_ = _buf["team_invite_expire_time"]; !_ok_ || __json_team_invite_expire_time__ == nil { err = errors.New("team_invite_expire_time error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_team_invite_expire_time__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.TeamInviteExpireTime = __x__ }}
    { var _ok_ bool; var __json_enable_cross_server_team__ interface{}; if __json_enable_cross_server_team__, _ok_ = _buf["enable_cross_server_team"]; !_ok_ || __json_enable_cross_server_team__ == nil { err = errors.New("enable_cross_server_team error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_enable_cross_server_team__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.EnableCrossServerTeam = __x__ }}
    return
}

