
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 道具类型
 */
const (
    /**
     * 消耗品
     */
    ItemType_Consumable = 1;
    /**
     * 装备
     */
    ItemType_Equipment = 2;
    /**
     * 货币
     */
    ItemType_Currency = 3;
    /**
     * 玩偶
     */
    ItemType_Doll = 4;
    /**
     * 家园道具
     */
    ItemType_HomeItem = 5;
    /**
     * 礼包
     */
    ItemType_GiftPack = 6;
    /**
     * 材料
     */
    ItemType_Material = 7;
    /**
     * 任务道具
     */
    ItemType_QuestItem = 8;
)

