
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type Item struct {
    Id int32
    Name string
    Type int32
    SubType int32
    Rarity int32
    Quality int32
    MaxStack int32
    Icon string
    Model string
    Description string
    CanTrade bool
    CanSell bool
    CanDrop bool
    CanDestroy bool
    BindType int32
    UseLevel int32
    UseVocation int32
    ExpireType int32
    ExpireTime int32
    UseSkillIds []int32
    Cooldown int32
    CooldownGroup int32
    Tags []string
    SortOrder int32
}

const TypeId_Item = 2289459

func (*Item) GetTypeId() int32 {
    return 2289459
}

func NewItem(_buf map[string]interface{}) (_v *Item, err error) {
    _v = &Item{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    { var _ok_ bool; var __json_type__ interface{}; if __json_type__, _ok_ = _buf["type"]; !_ok_ || __json_type__ == nil { err = errors.New("type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Type = __x__ }}
    { var _ok_ bool; var __json_sub_type__ interface{}; if __json_sub_type__, _ok_ = _buf["sub_type"]; !_ok_ || __json_sub_type__ == nil { err = errors.New("sub_type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_sub_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.SubType = __x__ }}
    { var _ok_ bool; var __json_rarity__ interface{}; if __json_rarity__, _ok_ = _buf["rarity"]; !_ok_ || __json_rarity__ == nil { err = errors.New("rarity error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_rarity__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Rarity = __x__ }}
    { var _ok_ bool; var __json_quality__ interface{}; if __json_quality__, _ok_ = _buf["quality"]; !_ok_ || __json_quality__ == nil { err = errors.New("quality error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_quality__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Quality = __x__ }}
    { var _ok_ bool; var __json_max_stack__ interface{}; if __json_max_stack__, _ok_ = _buf["max_stack"]; !_ok_ || __json_max_stack__ == nil { err = errors.New("max_stack error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_max_stack__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.MaxStack = __x__ }}
    { var _ok_ bool; var __json_icon__ interface{}; if __json_icon__, _ok_ = _buf["icon"]; !_ok_ || __json_icon__ == nil { err = errors.New("icon error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_icon__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Icon = __x__ }}
    { var _ok_ bool; var __json_model__ interface{}; if __json_model__, _ok_ = _buf["model"]; !_ok_ || __json_model__ == nil { err = errors.New("model error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_model__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Model = __x__ }}
    { var _ok_ bool; var __json_description__ interface{}; if __json_description__, _ok_ = _buf["description"]; !_ok_ || __json_description__ == nil { err = errors.New("description error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_description__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Description = __x__ }}
    { var _ok_ bool; var __json_can_trade__ interface{}; if __json_can_trade__, _ok_ = _buf["can_trade"]; !_ok_ || __json_can_trade__ == nil { err = errors.New("can_trade error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_can_trade__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CanTrade = __x__ }}
    { var _ok_ bool; var __json_can_sell__ interface{}; if __json_can_sell__, _ok_ = _buf["can_sell"]; !_ok_ || __json_can_sell__ == nil { err = errors.New("can_sell error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_can_sell__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CanSell = __x__ }}
    { var _ok_ bool; var __json_can_drop__ interface{}; if __json_can_drop__, _ok_ = _buf["can_drop"]; !_ok_ || __json_can_drop__ == nil { err = errors.New("can_drop error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_can_drop__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CanDrop = __x__ }}
    { var _ok_ bool; var __json_can_destroy__ interface{}; if __json_can_destroy__, _ok_ = _buf["can_destroy"]; !_ok_ || __json_can_destroy__ == nil { err = errors.New("can_destroy error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_can_destroy__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.CanDestroy = __x__ }}
    { var _ok_ bool; var __json_bind_type__ interface{}; if __json_bind_type__, _ok_ = _buf["bind_type"]; !_ok_ || __json_bind_type__ == nil { err = errors.New("bind_type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_bind_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.BindType = __x__ }}
    { var _ok_ bool; var __json_use_level__ interface{}; if __json_use_level__, _ok_ = _buf["use_level"]; !_ok_ || __json_use_level__ == nil { err = errors.New("use_level error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_use_level__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.UseLevel = __x__ }}
    { var _ok_ bool; var __json_use_vocation__ interface{}; if __json_use_vocation__, _ok_ = _buf["use_vocation"]; !_ok_ || __json_use_vocation__ == nil { err = errors.New("use_vocation error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_use_vocation__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.UseVocation = __x__ }}
    { var _ok_ bool; var __json_expire_type__ interface{}; if __json_expire_type__, _ok_ = _buf["expire_type"]; !_ok_ || __json_expire_type__ == nil { err = errors.New("expire_type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_expire_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ExpireType = __x__ }}
    { var _ok_ bool; var __json_expire_time__ interface{}; if __json_expire_time__, _ok_ = _buf["expire_time"]; !_ok_ || __json_expire_time__ == nil { err = errors.New("expire_time error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_expire_time__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ExpireTime = __x__ }}
    { var _ok_ bool; var __json_use_skill_ids__ interface{}; if __json_use_skill_ids__, _ok_ = _buf["use_skill_ids"]; !_ok_ || __json_use_skill_ids__ == nil { err = errors.New("use_skill_ids error"); return } else { var __x__ []int32;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_use_skill_ids__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]int32, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e0_.(float64); !_ok_ { err = errors.New("_list_v0_ error"); return }; _list_v0_ = int32(_x_) }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.UseSkillIds = __x__ }}
    { var _ok_ bool; var __json_cooldown__ interface{}; if __json_cooldown__, _ok_ = _buf["cooldown"]; !_ok_ || __json_cooldown__ == nil { err = errors.New("cooldown error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_cooldown__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Cooldown = __x__ }}
    { var _ok_ bool; var __json_cooldown_group__ interface{}; if __json_cooldown_group__, _ok_ = _buf["cooldown_group"]; !_ok_ || __json_cooldown_group__ == nil { err = errors.New("cooldown_group error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_cooldown_group__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.CooldownGroup = __x__ }}
    { var _ok_ bool; var __json_tags__ interface{}; if __json_tags__, _ok_ = _buf["tags"]; !_ok_ || __json_tags__ == nil { err = errors.New("tags error"); return } else { var __x__ []string;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_tags__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]string, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ string
                        {  if _list_v0_, _ok_ = _e0_.(string); !_ok_ { err = errors.New("_list_v0_ error"); return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.Tags = __x__ }}
    { var _ok_ bool; var __json_sort_order__ interface{}; if __json_sort_order__, _ok_ = _buf["sort_order"]; !_ok_ || __json_sort_order__ == nil { err = errors.New("sort_order error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_sort_order__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.SortOrder = __x__ }}
    return
}

