
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 稀有度
 */
const (
    /**
     * 普通
     */
    Rarity_Common = 1;
    /**
     * 优秀
     */
    Rarity_Uncommon = 2;
    /**
     * 稀有
     */
    Rarity_Rare = 3;
    /**
     * 史诗
     */
    Rarity_Epic = 4;
    /**
     * 传说
     */
    Rarity_Legendary = 5;
    /**
     * 神话
     */
    Rarity_Mythic = 6;
)

