
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 刷新类型
 */
const (
    /**
     * 永不刷新
     */
    RefreshType_Never = 0;
    /**
     * 每日刷新
     */
    RefreshType_Daily = 1;
    /**
     * 每周刷新
     */
    RefreshType_Weekly = 2;
    /**
     * 每月刷新
     */
    RefreshType_Monthly = 3;
)

