
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 商店类型
 */
const (
    /**
     * 神秘商店
     */
    ShopType_Mystery = 1;
    /**
     * 限时商店
     */
    ShopType_TimeLimited = 2;
    /**
     * 公会商店
     */
    ShopType_Guild = 3;
    /**
     * 联盟商店
     */
    ShopType_Alliance = 4;
    /**
     * 道具商店
     */
    ShopType_Item = 5;
)

