
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type ShopItemGuild struct {
    Id int32
    ShopId int32
    ItemId int32
    CurrencyType int32
    Price int32
    Discount int32
    StockType int32
    StockLimit int32
    UnlockLevel int32
    Position int32
    IsHot bool
    IsNew bool
    IsRecommend bool
    GuildLevelRequire int32
    GuildContributionMin int32
}

const TypeId_ShopItemGuild = -630051286

func (*ShopItemGuild) GetTypeId() int32 {
    return -630051286
}

func NewShopItemGuild(_buf map[string]interface{}) (_v *ShopItemGuild, err error) {
    _v = &ShopItemGuild{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_shop_id__ interface{}; if __json_shop_id__, _ok_ = _buf["shop_id"]; !_ok_ || __json_shop_id__ == nil { err = errors.New("shop_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_shop_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ShopId = __x__ }}
    { var _ok_ bool; var __json_item_id__ interface{}; if __json_item_id__, _ok_ = _buf["item_id"]; !_ok_ || __json_item_id__ == nil { err = errors.New("item_id error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_item_id__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ItemId = __x__ }}
    { var _ok_ bool; var __json_currency_type__ interface{}; if __json_currency_type__, _ok_ = _buf["currency_type"]; !_ok_ || __json_currency_type__ == nil { err = errors.New("currency_type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_currency_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.CurrencyType = __x__ }}
    { var _ok_ bool; var __json_price__ interface{}; if __json_price__, _ok_ = _buf["price"]; !_ok_ || __json_price__ == nil { err = errors.New("price error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_price__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Price = __x__ }}
    { var _ok_ bool; var __json_discount__ interface{}; if __json_discount__, _ok_ = _buf["discount"]; !_ok_ || __json_discount__ == nil { err = errors.New("discount error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_discount__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Discount = __x__ }}
    { var _ok_ bool; var __json_stock_type__ interface{}; if __json_stock_type__, _ok_ = _buf["stock_type"]; !_ok_ || __json_stock_type__ == nil { err = errors.New("stock_type error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_stock_type__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.StockType = __x__ }}
    { var _ok_ bool; var __json_stock_limit__ interface{}; if __json_stock_limit__, _ok_ = _buf["stock_limit"]; !_ok_ || __json_stock_limit__ == nil { err = errors.New("stock_limit error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_stock_limit__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.StockLimit = __x__ }}
    { var _ok_ bool; var __json_unlock_level__ interface{}; if __json_unlock_level__, _ok_ = _buf["unlock_level"]; !_ok_ || __json_unlock_level__ == nil { err = errors.New("unlock_level error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_unlock_level__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.UnlockLevel = __x__ }}
    { var _ok_ bool; var __json_position__ interface{}; if __json_position__, _ok_ = _buf["position"]; !_ok_ || __json_position__ == nil { err = errors.New("position error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_position__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Position = __x__ }}
    { var _ok_ bool; var __json_is_hot__ interface{}; if __json_is_hot__, _ok_ = _buf["is_hot"]; !_ok_ || __json_is_hot__ == nil { err = errors.New("is_hot error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_is_hot__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.IsHot = __x__ }}
    { var _ok_ bool; var __json_is_new__ interface{}; if __json_is_new__, _ok_ = _buf["is_new"]; !_ok_ || __json_is_new__ == nil { err = errors.New("is_new error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_is_new__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.IsNew = __x__ }}
    { var _ok_ bool; var __json_is_recommend__ interface{}; if __json_is_recommend__, _ok_ = _buf["is_recommend"]; !_ok_ || __json_is_recommend__ == nil { err = errors.New("is_recommend error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_is_recommend__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.IsRecommend = __x__ }}
    { var _ok_ bool; var __json_guild_level_require__ interface{}; if __json_guild_level_require__, _ok_ = _buf["guild_level_require"]; !_ok_ || __json_guild_level_require__ == nil { err = errors.New("guild_level_require error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_guild_level_require__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.GuildLevelRequire = __x__ }}
    { var _ok_ bool; var __json_guild_contribution_min__ interface{}; if __json_guild_contribution_min__, _ok_ = _buf["guild_contribution_min"]; !_ok_ || __json_guild_contribution_min__ == nil { err = errors.New("guild_contribution_min error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_guild_contribution_min__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.GuildContributionMin = __x__ }}
    return
}

