
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type ShopItemBase struct {
    Id int32
    ShopId int32
    ItemId int32
    CurrencyType int32
    Price int32
    Discount int32
    StockType int32
    StockLimit int32
    UnlockLevel int32
    Position int32
    IsHot bool
    IsNew bool
    IsRecommend bool
}

const TypeId_ShopItemBase = 256602554

func (*ShopItemBase) GetTypeId() int32 {
    return 256602554
}

func NewShopItemBase(_buf map[string]interface{}) (interface{}, error) {
    var id string
    var _ok_ bool
    if id, _ok_ = _buf["$type"].(string) ; !_ok_ {
        return nil, errors.New("type id missing")
    }
    switch id {
        case "ShopItemNormal": _v, err := NewShopItemNormal(_buf); if err != nil { return nil, errors.New("shopitemnormal") } else { return _v, nil }
        case "ShopItemMystery": _v, err := NewShopItemMystery(_buf); if err != nil { return nil, errors.New("shopitemmystery") } else { return _v, nil }
        case "ShopItemGuild": _v, err := NewShopItemGuild(_buf); if err != nil { return nil, errors.New("shopitemguild") } else { return _v, nil }
        case "ShopItemAlliance": _v, err := NewShopItemAlliance(_buf); if err != nil { return nil, errors.New("shopitemalliance") } else { return _v, nil }
        case "ShopItemTimeLimited": _v, err := NewShopItemTimeLimited(_buf); if err != nil { return nil, errors.New("shopitemtimelimited") } else { return _v, nil }
        default: return nil, errors.New("unknown type id")
    }
}


