
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

/**
 * 库存类型
 */
const (
    /**
     * 无限库存
     */
    StockType_Unlimited = 0;
    /**
     * 每日限购
     */
    StockType_Daily = 1;
    /**
     * 每周限购
     */
    StockType_Weekly = 2;
    /**
     * 每月限购
     */
    StockType_Monthly = 3;
    /**
     * 终身限购
     */
    StockType_Lifetime = 4;
)

