
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

type JsonLoader func(string) ([]map[string]interface{}, error)

type Tables struct {
    TbGlobalConfig *TbGlobalConfig
    TbItem *TbItem
    TbShopItem *TbShopItem
}

func NewTables(loader JsonLoader) (*Tables, error) {
    var err error
    var buf []map[string]interface{}

    tables := &Tables{}
    if buf, err = loader("tbglobalconfig") ; err != nil {
        return nil, err
    }
    if tables.TbGlobalConfig, err = NewTbGlobalConfig(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbitem") ; err != nil {
        return nil, err
    }
    if tables.TbItem, err = NewTbItem(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbshopitem") ; err != nil {
        return nil, err
    }
    if tables.TbShopItem, err = NewTbShopItem(buf) ; err != nil {
        return nil, err
    }
    return tables, nil
}


