
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;



import "errors"

type TbGlobalConfig struct {
    _data *GlobalConfig
}

func NewTbGlobalConfig(_buf []map[string]interface{}) (*TbGlobalConfig, error) {
	if len(_buf) != 1 {
        return nil, errors.New(" size != 1 ")
	} else {
		if _v, err2 := NewGlobalConfig(_buf[0]); err2 != nil {
			return nil, err2
		} else {
		    return &TbGlobalConfig{_data:_v}, nil
		}
	}
}

func (table *TbGlobalConfig) Get() *GlobalConfig {
    return table._data
}


