
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type TbShopItem struct {
    _dataMap map[int32]interface{}
    _dataList []interface{}
}

func NewTbShopItem(_buf []map[string]interface{}) (*TbShopItem, error) {
    _dataList := make([]interface{}, 0, len(_buf))
    dataMap := make(map[int32]interface{})

    for _, _ele_ := range _buf {
        if _v, err2 := NewShopItemBase(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            if __v, __is := _v.(*ShopItemNormal) ; __is {
                dataMap[__v.Id] = _v
                continue
            }
            if __v, __is := _v.(*ShopItemMystery) ; __is {
                dataMap[__v.Id] = _v
                continue
            }
            if __v, __is := _v.(*ShopItemGuild) ; __is {
                dataMap[__v.Id] = _v
                continue
            }
            if __v, __is := _v.(*ShopItemAlliance) ; __is {
                dataMap[__v.Id] = _v
                continue
            }
            if __v, __is := _v.(*ShopItemTimeLimited) ; __is {
                dataMap[__v.Id] = _v
                continue
            }
        }
    }
    return &TbShopItem{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbShopItem) GetDataMap() map[int32]interface{} {
    return table._dataMap
}

func (table *TbShopItem) GetDataList() []interface{} {
    return table._dataList
}

func (table *TbShopItem) Get(key int32) interface{} {
    return table._dataMap[key]
}


