
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 绑定类型
    /// </summary>
    public enum BindType
    {
        /// <summary>
        /// 不绑定
        /// </summary>
        None = 0,
        /// <summary>
        /// 拾取绑定
        /// </summary>
        PickupBind = 1,
        /// <summary>
        /// 装备绑定
        /// </summary>
        EquipBind = 2,
    }

} 

