
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 货币类型
    /// </summary>
    public enum CurrencyType
    {
        /// <summary>
        /// 金币
        /// </summary>
        Coin = 1,
        /// <summary>
        /// 钻石
        /// </summary>
        Diamond = 2,
        /// <summary>
        /// 公会币
        /// </summary>
        GuildCoin = 3,
        /// <summary>
        /// 联盟币
        /// </summary>
        AllianceCoin = 4,
        /// <summary>
        /// 荣誉点
        /// </summary>
        HonorPoint = 5,
    }

} 

