
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 过期类型
    /// </summary>
    public enum ExpireType
    {
        /// <summary>
        /// 永久
        /// </summary>
        Permanent = 0,
        /// <summary>
        /// 时长
        /// </summary>
        Duration = 1,
        /// <summary>
        /// 固定日期
        /// </summary>
        FixedDate = 2,
    }

} 

