
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
/// <summary>
/// 全局配置
/// </summary>
public sealed partial class GlobalConfig : Luban.BeanBase
{
    public GlobalConfig(JsonElement _buf) 
    {
        TeamMaxMembers = _buf.GetProperty("team_max_members").GetInt32();
        TeamInviteMaxCount = _buf.GetProperty("team_invite_max_count").GetInt32();
        TeamInviteExpireTime = _buf.GetProperty("team_invite_expire_time").GetInt32();
        EnableCrossServerTeam = _buf.GetProperty("enable_cross_server_team").GetBoolean();
    }

    public static GlobalConfig DeserializeGlobalConfig(JsonElement _buf)
    {
        return new GlobalConfig(_buf);
    }

    /// <summary>
    /// 组队人数上限
    /// </summary>
    public readonly int TeamMaxMembers;
    /// <summary>
    /// 同时邀请组队人数上限
    /// </summary>
    public readonly int TeamInviteMaxCount;
    /// <summary>
    /// 邀请组队过期时间（秒）
    /// </summary>
    public readonly int TeamInviteExpireTime;
    /// <summary>
    /// 是否开启跨服组队
    /// </summary>
    public readonly bool EnableCrossServerTeam;
   
    public const int __ID__ = -958250779;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "teamMaxMembers:" + TeamMaxMembers + ","
        + "teamInviteMaxCount:" + TeamInviteMaxCount + ","
        + "teamInviteExpireTime:" + TeamInviteExpireTime + ","
        + "enableCrossServerTeam:" + EnableCrossServerTeam + ","
        + "}";
    }
}
}

