
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
/// <summary>
/// 道具
/// </summary>
public sealed partial class Item : Luban.BeanBase
{
    public Item(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetInt32();
        Name = _buf.GetProperty("name").GetString();
        Type = (ItemType)_buf.GetProperty("type").GetInt32();
        SubType = _buf.GetProperty("sub_type").GetInt32();
        Rarity = (Rarity)_buf.GetProperty("rarity").GetInt32();
        Quality = _buf.GetProperty("quality").GetInt32();
        MaxStack = _buf.GetProperty("max_stack").GetInt32();
        Icon = _buf.GetProperty("icon").GetString();
        Model = _buf.GetProperty("model").GetString();
        Description = _buf.GetProperty("description").GetString();
        CanTrade = _buf.GetProperty("can_trade").GetBoolean();
        CanSell = _buf.GetProperty("can_sell").GetBoolean();
        CanDrop = _buf.GetProperty("can_drop").GetBoolean();
        CanDestroy = _buf.GetProperty("can_destroy").GetBoolean();
        BindType = (BindType)_buf.GetProperty("bind_type").GetInt32();
        UseLevel = _buf.GetProperty("use_level").GetInt32();
        UseVocation = _buf.GetProperty("use_vocation").GetInt32();
        ExpireType = (ExpireType)_buf.GetProperty("expire_type").GetInt32();
        ExpireTime = _buf.GetProperty("expire_time").GetInt32();
        { var __json0 = _buf.GetProperty("use_skill_ids"); UseSkillIds = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  UseSkillIds.Add(__v0); }   }
        Cooldown = _buf.GetProperty("cooldown").GetInt32();
        CooldownGroup = _buf.GetProperty("cooldown_group").GetInt32();
        { var __json0 = _buf.GetProperty("tags"); Tags = new System.Collections.Generic.List<string>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { string __v0;  __v0 = __e0.GetString();  Tags.Add(__v0); }   }
        SortOrder = _buf.GetProperty("sort_order").GetInt32();
    }

    public static Item DeserializeItem(JsonElement _buf)
    {
        return new Item(_buf);
    }

    /// <summary>
    /// 道具ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 道具类型
    /// </summary>
    public readonly ItemType Type;
    /// <summary>
    /// 子类型
    /// </summary>
    public readonly int SubType;
    /// <summary>
    /// 稀有度
    /// </summary>
    public readonly Rarity Rarity;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Quality;
    /// <summary>
    /// 最大堆叠数量
    /// </summary>
    public readonly int MaxStack;
    /// <summary>
    /// 图标资源路径
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 3D模型资源路径
    /// </summary>
    public readonly string Model;
    /// <summary>
    /// 道具描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 是否可交易
    /// </summary>
    public readonly bool CanTrade;
    /// <summary>
    /// 是否可出售给NPC
    /// </summary>
    public readonly bool CanSell;
    /// <summary>
    /// 是否可掉落
    /// </summary>
    public readonly bool CanDrop;
    /// <summary>
    /// 是否可销毁
    /// </summary>
    public readonly bool CanDestroy;
    /// <summary>
    /// 绑定类型
    /// </summary>
    public readonly BindType BindType;
    /// <summary>
    /// 使用等级限制
    /// </summary>
    public readonly int UseLevel;
    /// <summary>
    /// 职业限制
    /// </summary>
    public readonly int UseVocation;
    /// <summary>
    /// 过期类型
    /// </summary>
    public readonly ExpireType ExpireType;
    /// <summary>
    /// 过期时间
    /// </summary>
    public readonly int ExpireTime;
    /// <summary>
    /// 使用技能ID列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> UseSkillIds;
    /// <summary>
    /// 冷却时间（毫秒）
    /// </summary>
    public readonly int Cooldown;
    /// <summary>
    /// 冷却组ID
    /// </summary>
    public readonly int CooldownGroup;
    /// <summary>
    /// 标签列表
    /// </summary>
    public readonly System.Collections.Generic.List<string> Tags;
    /// <summary>
    /// 排序权重
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = 2289459;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "type:" + Type + ","
        + "subType:" + SubType + ","
        + "rarity:" + Rarity + ","
        + "quality:" + Quality + ","
        + "maxStack:" + MaxStack + ","
        + "icon:" + Icon + ","
        + "model:" + Model + ","
        + "description:" + Description + ","
        + "canTrade:" + CanTrade + ","
        + "canSell:" + CanSell + ","
        + "canDrop:" + CanDrop + ","
        + "canDestroy:" + CanDestroy + ","
        + "bindType:" + BindType + ","
        + "useLevel:" + UseLevel + ","
        + "useVocation:" + UseVocation + ","
        + "expireType:" + ExpireType + ","
        + "expireTime:" + ExpireTime + ","
        + "useSkillIds:" + Luban.StringUtil.CollectionToString(UseSkillIds) + ","
        + "cooldown:" + Cooldown + ","
        + "cooldownGroup:" + CooldownGroup + ","
        + "tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "sortOrder:" + SortOrder + ","
        + "}";
    }
}
}

