
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 道具类型
    /// </summary>
    public enum ItemType
    {
        /// <summary>
        /// 消耗品
        /// </summary>
        Consumable = 1,
        /// <summary>
        /// 装备
        /// </summary>
        Equipment = 2,
        /// <summary>
        /// 货币
        /// </summary>
        Currency = 3,
        /// <summary>
        /// 玩偶
        /// </summary>
        Doll = 4,
        /// <summary>
        /// 家园道具
        /// </summary>
        HomeItem = 5,
        /// <summary>
        /// 礼包
        /// </summary>
        GiftPack = 6,
        /// <summary>
        /// 材料
        /// </summary>
        Material = 7,
        /// <summary>
        /// 任务道具
        /// </summary>
        QuestItem = 8,
    }

} 

