
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 稀有度
    /// </summary>
    public enum Rarity
    {
        /// <summary>
        /// 普通
        /// </summary>
        Common = 1,
        /// <summary>
        /// 优秀
        /// </summary>
        Uncommon = 2,
        /// <summary>
        /// 稀有
        /// </summary>
        Rare = 3,
        /// <summary>
        /// 史诗
        /// </summary>
        Epic = 4,
        /// <summary>
        /// 传说
        /// </summary>
        Legendary = 5,
        /// <summary>
        /// 神话
        /// </summary>
        Mythic = 6,
    }

} 

