
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 刷新类型
    /// </summary>
    public enum RefreshType
    {
        /// <summary>
        /// 永不刷新
        /// </summary>
        Never = 0,
        /// <summary>
        /// 每日刷新
        /// </summary>
        Daily = 1,
        /// <summary>
        /// 每周刷新
        /// </summary>
        Weekly = 2,
        /// <summary>
        /// 每月刷新
        /// </summary>
        Monthly = 3,
    }

} 

