
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
/// <summary>
/// 限时商店道具
/// </summary>
public sealed partial class ShopItemTimeLimited : ShopItemBase
{
    public ShopItemTimeLimited(JsonElement _buf)  : base(_buf) 
    {
        StartTime = _buf.GetProperty("start_time").GetInt64();
        EndTime = _buf.GetProperty("end_time").GetInt64();
    }

    public static ShopItemTimeLimited DeserializeShopItemTimeLimited(JsonElement _buf)
    {
        return new ShopItemTimeLimited(_buf);
    }

    /// <summary>
    /// 开始时间（Unix时间戳）
    /// </summary>
    public readonly long StartTime;
    /// <summary>
    /// 结束时间（Unix时间戳）
    /// </summary>
    public readonly long EndTime;
   
    public const int __ID__ = 591099652;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "shopId:" + ShopId + ","
        + "itemId:" + ItemId + ","
        + "currencyType:" + CurrencyType + ","
        + "price:" + Price + ","
        + "discount:" + Discount + ","
        + "stockType:" + StockType + ","
        + "stockLimit:" + StockLimit + ","
        + "unlockLevel:" + UnlockLevel + ","
        + "position:" + Position + ","
        + "isHot:" + IsHot + ","
        + "isNew:" + IsNew + ","
        + "isRecommend:" + IsRecommend + ","
        + "startTime:" + StartTime + ","
        + "endTime:" + EndTime + ","
        + "}";
    }
}
}

