
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
/// <summary>
/// 商店道具基类
/// </summary>
public abstract partial class ShopItemBase : Luban.BeanBase
{
    public ShopItemBase(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetInt32();
        ShopId = _buf.GetProperty("shop_id").GetInt32();
        ItemId = _buf.GetProperty("item_id").GetInt32();
        CurrencyType = (CurrencyType)_buf.GetProperty("currency_type").GetInt32();
        Price = _buf.GetProperty("price").GetInt32();
        Discount = _buf.GetProperty("discount").GetInt32();
        StockType = (StockType)_buf.GetProperty("stock_type").GetInt32();
        StockLimit = _buf.GetProperty("stock_limit").GetInt32();
        UnlockLevel = _buf.GetProperty("unlock_level").GetInt32();
        Position = _buf.GetProperty("position").GetInt32();
        IsHot = _buf.GetProperty("is_hot").GetBoolean();
        IsNew = _buf.GetProperty("is_new").GetBoolean();
        IsRecommend = _buf.GetProperty("is_recommend").GetBoolean();
    }

    public static ShopItemBase DeserializeShopItemBase(JsonElement _buf)
    {
        switch (_buf.GetProperty("$type").GetString())
        {
            case "ShopItemNormal": return new ShopItemNormal(_buf);
            case "ShopItemMystery": return new ShopItemMystery(_buf);
            case "ShopItemGuild": return new ShopItemGuild(_buf);
            case "ShopItemAlliance": return new ShopItemAlliance(_buf);
            case "ShopItemTimeLimited": return new ShopItemTimeLimited(_buf);
            default: throw new SerializationException();
        }
    }

    /// <summary>
    /// 配置ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属商店ID
    /// </summary>
    public readonly int ShopId;
    /// <summary>
    /// 道具ID
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 货币类型
    /// </summary>
    public readonly CurrencyType CurrencyType;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 折扣百分比
    /// </summary>
    public readonly int Discount;
    /// <summary>
    /// 库存类型
    /// </summary>
    public readonly StockType StockType;
    /// <summary>
    /// 库存数量
    /// </summary>
    public readonly int StockLimit;
    /// <summary>
    /// 解锁等级
    /// </summary>
    public readonly int UnlockLevel;
    /// <summary>
    /// 显示位置
    /// </summary>
    public readonly int Position;
    /// <summary>
    /// 热卖标签
    /// </summary>
    public readonly bool IsHot;
    /// <summary>
    /// 新品标签
    /// </summary>
    public readonly bool IsNew;
    /// <summary>
    /// 推荐标签
    /// </summary>
    public readonly bool IsRecommend;
   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "shopId:" + ShopId + ","
        + "itemId:" + ItemId + ","
        + "currencyType:" + CurrencyType + ","
        + "price:" + Price + ","
        + "discount:" + Discount + ","
        + "stockType:" + StockType + ","
        + "stockLimit:" + StockLimit + ","
        + "unlockLevel:" + UnlockLevel + ","
        + "position:" + Position + ","
        + "isHot:" + IsHot + ","
        + "isNew:" + IsNew + ","
        + "isRecommend:" + IsRecommend + ","
        + "}";
    }
}
}

