
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
/// <summary>
/// 公会商店道具
/// </summary>
public sealed partial class ShopItemGuild : ShopItemBase
{
    public ShopItemGuild(JsonElement _buf)  : base(_buf) 
    {
        GuildLevelRequire = _buf.GetProperty("guild_level_require").GetInt32();
        GuildContributionMin = _buf.GetProperty("guild_contribution_min").GetInt32();
    }

    public static ShopItemGuild DeserializeShopItemGuild(JsonElement _buf)
    {
        return new ShopItemGuild(_buf);
    }

    /// <summary>
    /// 公会等级要求
    /// </summary>
    public readonly int GuildLevelRequire;
    /// <summary>
    /// 公会贡献度要求
    /// </summary>
    public readonly int GuildContributionMin;
   
    public const int __ID__ = -630051286;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "shopId:" + ShopId + ","
        + "itemId:" + ItemId + ","
        + "currencyType:" + CurrencyType + ","
        + "price:" + Price + ","
        + "discount:" + Discount + ","
        + "stockType:" + StockType + ","
        + "stockLimit:" + StockLimit + ","
        + "unlockLevel:" + UnlockLevel + ","
        + "position:" + Position + ","
        + "isHot:" + IsHot + ","
        + "isNew:" + IsNew + ","
        + "isRecommend:" + IsRecommend + ","
        + "guildLevelRequire:" + GuildLevelRequire + ","
        + "guildContributionMin:" + GuildContributionMin + ","
        + "}";
    }
}
}

