
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 商店类型
    /// </summary>
    public enum ShopType
    {
        /// <summary>
        /// 神秘商店
        /// </summary>
        Mystery = 1,
        /// <summary>
        /// 限时商店
        /// </summary>
        TimeLimited = 2,
        /// <summary>
        /// 公会商店
        /// </summary>
        Guild = 3,
        /// <summary>
        /// 联盟商店
        /// </summary>
        Alliance = 4,
        /// <summary>
        /// 道具商店
        /// </summary>
        Item = 5,
    }

} 

