
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
/// <summary>
/// 普通商店道具
/// </summary>
public sealed partial class ShopItemNormal : ShopItemBase
{
    public ShopItemNormal(JsonElement _buf)  : base(_buf) 
    {
    }

    public static ShopItemNormal DeserializeShopItemNormal(JsonElement _buf)
    {
        return new ShopItemNormal(_buf);
    }

   
    public const int __ID__ = 2138378640;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "shopId:" + ShopId + ","
        + "itemId:" + ItemId + ","
        + "currencyType:" + CurrencyType + ","
        + "price:" + Price + ","
        + "discount:" + Discount + ","
        + "stockType:" + StockType + ","
        + "stockLimit:" + StockLimit + ","
        + "unlockLevel:" + UnlockLevel + ","
        + "position:" + Position + ","
        + "isHot:" + IsHot + ","
        + "isNew:" + IsNew + ","
        + "isRecommend:" + IsRecommend + ","
        + "}";
    }
}
}

