
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
/// <summary>
/// 联盟商店道具
/// </summary>
public sealed partial class ShopItemAlliance : ShopItemBase
{
    public ShopItemAlliance(JsonElement _buf)  : base(_buf) 
    {
        AllianceLevelRequire = _buf.GetProperty("alliance_level_require").GetInt32();
        AllianceContributionMin = _buf.GetProperty("alliance_contribution_min").GetInt32();
    }

    public static ShopItemAlliance DeserializeShopItemAlliance(JsonElement _buf)
    {
        return new ShopItemAlliance(_buf);
    }

    /// <summary>
    /// 联盟等级要求
    /// </summary>
    public readonly int AllianceLevelRequire;
    /// <summary>
    /// 联盟贡献度要求
    /// </summary>
    public readonly int AllianceContributionMin;
   
    public const int __ID__ = -2032167264;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "shopId:" + ShopId + ","
        + "itemId:" + ItemId + ","
        + "currencyType:" + CurrencyType + ","
        + "price:" + Price + ","
        + "discount:" + Discount + ","
        + "stockType:" + StockType + ","
        + "stockLimit:" + StockLimit + ","
        + "unlockLevel:" + UnlockLevel + ","
        + "position:" + Position + ","
        + "isHot:" + IsHot + ","
        + "isNew:" + IsNew + ","
        + "isRecommend:" + IsRecommend + ","
        + "allianceLevelRequire:" + AllianceLevelRequire + ","
        + "allianceContributionMin:" + AllianceContributionMin + ","
        + "}";
    }
}
}

