
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
/// <summary>
/// 神秘商店道具
/// </summary>
public sealed partial class ShopItemMystery : ShopItemBase
{
    public ShopItemMystery(JsonElement _buf)  : base(_buf) 
    {
        Weight = _buf.GetProperty("weight").GetInt32();
    }

    public static ShopItemMystery DeserializeShopItemMystery(JsonElement _buf)
    {
        return new ShopItemMystery(_buf);
    }

    /// <summary>
    /// 权重（0=固定出现）
    /// </summary>
    public readonly int Weight;
   
    public const int __ID__ = 1265152438;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "shopId:" + ShopId + ","
        + "itemId:" + ItemId + ","
        + "currencyType:" + CurrencyType + ","
        + "price:" + Price + ","
        + "discount:" + Discount + ","
        + "stockType:" + StockType + ","
        + "stockLimit:" + StockLimit + ","
        + "unlockLevel:" + UnlockLevel + ","
        + "position:" + Position + ","
        + "isHot:" + IsHot + ","
        + "isNew:" + IsNew + ","
        + "isRecommend:" + IsRecommend + ","
        + "weight:" + Weight + ","
        + "}";
    }
}
}

