
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 库存类型
    /// </summary>
    public enum StockType
    {
        /// <summary>
        /// 无限库存
        /// </summary>
        Unlimited = 0,
        /// <summary>
        /// 每日限购
        /// </summary>
        Daily = 1,
        /// <summary>
        /// 每周限购
        /// </summary>
        Weekly = 2,
        /// <summary>
        /// 每月限购
        /// </summary>
        Monthly = 3,
        /// <summary>
        /// 终身限购
        /// </summary>
        Lifetime = 4,
    }

} 

