
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;

namespace cfg
{
public partial class Tables
{
    /// <summary>
    /// 全局配置表
    /// </summary>
    public TbGlobalConfig TbGlobalConfig {get; }
    /// <summary>
    /// 道具表
    /// </summary>
    public TbItem TbItem {get; }
    /// <summary>
    /// 商店道具表
    /// </summary>
    public TbShopItem TbShopItem {get; }

    public Tables(System.Func<string, JsonElement> loader)
    {
        TbGlobalConfig = new TbGlobalConfig(loader("tbglobalconfig"));
        TbItem = new TbItem(loader("tbitem"));
        TbShopItem = new TbShopItem(loader("tbshopitem"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbGlobalConfig.ResolveRef(this);
        TbItem.ResolveRef(this);
        TbShopItem.ResolveRef(this);
    }
}

}
