
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
/// <summary>
/// 全局配置表
/// </summary>
public partial class TbGlobalConfig
{

     private readonly GlobalConfig _data;

     public GlobalConfig Data => _data;

    public TbGlobalConfig(JsonElement _buf)
    {
        int n = _buf.GetArrayLength();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::cfg.GlobalConfig.DeserializeGlobalConfig(_buf[0]);
    }


    /// <summary>
    /// 组队人数上限
    /// </summary>
     public int TeamMaxMembers => _data.TeamMaxMembers;
    /// <summary>
    /// 同时邀请组队人数上限
    /// </summary>
     public int TeamInviteMaxCount => _data.TeamInviteMaxCount;
    /// <summary>
    /// 邀请组队过期时间（秒）
    /// </summary>
     public int TeamInviteExpireTime => _data.TeamInviteExpireTime;
    /// <summary>
    /// 是否开启跨服组队
    /// </summary>
     public bool EnableCrossServerTeam => _data.EnableCrossServerTeam;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

