
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg
{
/// <summary>
/// 商店道具表
/// </summary>
public partial class TbShopItem
{
    private readonly System.Collections.Generic.Dictionary<int, ShopItemBase> _dataMap;
    private readonly System.Collections.Generic.List<ShopItemBase> _dataList;
    
    public TbShopItem(JsonElement _buf)
    {
        int count = _buf.GetArrayLength();
        _dataMap = new System.Collections.Generic.Dictionary<int, ShopItemBase>(count);
        _dataList = new System.Collections.Generic.List<ShopItemBase>(count);
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            ShopItemBase _v;
            _v = global::cfg.ShopItemBase.DeserializeShopItemBase(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ShopItemBase> DataMap => _dataMap;
    public System.Collections.Generic.List<ShopItemBase> DataList => _dataList;

    public T GetOrDefaultAs<T>(int key) where T : ShopItemBase => _dataMap.TryGetValue(key, out var v) ? (T)v : default;
    public T GetAs<T>(int key) where T : ShopItemBase => (T)_dataMap[key];
    public ShopItemBase GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ShopItemBase Get(int key) => _dataMap[key];
    public ShopItemBase this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

