
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.config
{
/// <summary>
/// 日期时间类型，支持多种格式
/// </summary>
public sealed partial class DateTime : Luban.BeanBase
{
    public DateTime(JsonElement _buf) 
    {
        Value = _buf.GetProperty("value").GetInt64();
    }

    public static DateTime DeserializeDateTime(JsonElement _buf)
    {
        return new config.DateTime(_buf);
    }

    /// <summary>
    /// 时间值
    /// </summary>
    public readonly long Value;
   
    public const int __ID__ = -1435202329;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "value:" + Value + ","
        + "}";
    }
}
}

