
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.config
{
/// <summary>
/// 时间范围，格式: start~end
/// </summary>
public sealed partial class DateTimeRange : Luban.BeanBase
{
    public DateTimeRange(JsonElement _buf) 
    {
        StartTime = _buf.GetProperty("start_time").GetInt64();
        EndTime = _buf.GetProperty("end_time").GetInt64();
    }

    public static DateTimeRange DeserializeDateTimeRange(JsonElement _buf)
    {
        return new config.DateTimeRange(_buf);
    }

    /// <summary>
    /// 开始时间
    /// </summary>
    public readonly long StartTime;
    /// <summary>
    /// 结束时间
    /// </summary>
    public readonly long EndTime;
   
    public const int __ID__ = 862172310;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "startTime:" + StartTime + ","
        + "endTime:" + EndTime + ","
        + "}";
    }
}
}

