
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.config
{
/// <summary>
/// 时间点，格式: HH:mm:ss
/// </summary>
public sealed partial class TimeOfDay : Luban.BeanBase
{
    public TimeOfDay(JsonElement _buf) 
    {
        Hour = _buf.GetProperty("hour").GetInt32();
        Minute = _buf.GetProperty("minute").GetInt32();
        Second = _buf.GetProperty("second").GetInt32();
    }

    public static TimeOfDay DeserializeTimeOfDay(JsonElement _buf)
    {
        return new config.TimeOfDay(_buf);
    }

    /// <summary>
    /// 小时(0-23)
    /// </summary>
    public readonly int Hour;
    /// <summary>
    /// 分钟(0-59)
    /// </summary>
    public readonly int Minute;
    /// <summary>
    /// 秒(0-59)
    /// </summary>
    public readonly int Second;
   
    public const int __ID__ = -1260823636;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "hour:" + Hour + ","
        + "minute:" + Minute + ","
        + "second:" + Second + ","
        + "}";
    }
}
}

