
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace cfg.config
{
/// <summary>
/// 时间段范围，格式: HH:mm:ss;HH:mm:ss
/// </summary>
public sealed partial class TimeOfDayRange : Luban.BeanBase
{
    public TimeOfDayRange(JsonElement _buf) 
    {
        StartTime = global::cfg.config.TimeOfDay.DeserializeTimeOfDay(_buf.GetProperty("start_time"));
        EndTime = global::cfg.config.TimeOfDay.DeserializeTimeOfDay(_buf.GetProperty("end_time"));
    }

    public static TimeOfDayRange DeserializeTimeOfDayRange(JsonElement _buf)
    {
        return new config.TimeOfDayRange(_buf);
    }

    /// <summary>
    /// 开始时间点
    /// </summary>
    public readonly config.TimeOfDay StartTime;
    /// <summary>
    /// 结束时间点
    /// </summary>
    public readonly config.TimeOfDay EndTime;
   
    public const int __ID__ = -570795791;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        StartTime?.ResolveRef(tables);
        EndTime?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "startTime:" + StartTime + ","
        + "endTime:" + EndTime + ","
        + "}";
    }
}
}

